# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :signing do
	sync_code_signing(type: "development",
		generate_apple_certs: false,
		app_identifier: "trmquang.frameproject",
		username: "trmquang0109@gmail.com",
		storage_mode: "git",
		git_url: "git@github.com:trmquangbiz/frame-project-development-certificate.git",
		readonly: true)
	sync_code_signing(type: "appstore",
		generate_apple_certs: false,
		app_identifier: "trmquang.frameproject",
		username: "trmquang.frameproject",
		storage_mode: "git",
		git_url: "git@github.com:trmquangbiz/frame-project-production-certificate.git",
		readonly: true)
  end
  lane :beta do
       build_app(scheme: "frameproject")
  end
end
